config/routes.rb
TinyListing::Application.routes.draw do
  root 'welcome#index'
  
  devise_for :users, skip: [:registrations, :sessions]

  get '/signin' => 'welcome#index', as: :user_session

  devise_scope :user do
    post 'signin' => 'devise/sessions#create'
    delete 'signout' => 'devise/sessions#destroy'
  end

  get '/search' => "search#new", as: :search
  post '/search' => "search#create"

  resources :repositories, only: [:index, :new, :create, :show, :update]
end

app/models/loot.rb
require 'uri'

class Loot < ActiveRecord::Base
  include ActiveSupport::Inflector

  BASIC_EXTENSIONS = %w(
    avi mkv mp4
    mp3 ogg flac
    pdf epub
    tar.gz tgz rar zip
    dmg iso
  )
  belongs_to :repository

  before_save :extract_name_from_link
  before_save :extract_name_sanitize
  before_save :extract_extension_from_link

  def extract_name_from_link
    if self[:name].blank?
      name_raw = self[:link].split('/').last
      name_splitted = name_raw.split('.')

      if name_splitted.length > 1
        name_splitted.delete_at(-1)
        name = name_splitted.join(" ")
      else
        name = name_splitted.first
      end

      self[:name] = URI.decode(name)
    end
  end

  def extract_name_sanitize
    if self[:name_sanitize].blank?
      self[:name_sanitize] = transliterate(self[:name]).gsub(/-|_/," ").strip
    end
  end

  def extract_extension_from_link
    self[:extension] = self[:link].split('.').last if self[:extension].blank?
  end
end

app/models/repository.rb
class Repository < ActiveRecord::Base
  has_many :loots, dependent: :destroy
  belongs_to :user

  validates_presence_of :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :repositories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :authenticate_user!
end

app/controllers/repositories_controller.rb
require 'vacuum'

class RepositoriesController < ApplicationController
  def index
    @repositories = Repository.all
  end

  def new
    @repository = Repository.new
  end

  def show
    @repository = Repository.find(params[:id])
  end

  def create
    register_repository = RegisterRepository.call(register_repository_params)

    if register_repository.success?
      redirect_to root_path, notice: "Loots on #{register_repository.repository.link} in progress!"
    else
      redirect_to new_repository_path, alert: "Something went wrong: #{register_repository.message}"
    end
  end

  private

  def register_repository_params
    params.require(:repository).permit(:link).merge({
      user_id: current_user.id
    })
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_filter :loot

  def new
  end

  def create
    if loot_params.empty?
      @loots = []
      flash.now.alert = "No matches found"
    else
      @loots = Loot.basic_search(loot_params)

      if @loots.empty?
        flash.now.alert = "No matches found"
      else
        flash.now.notice = "Found #{@loots.to_a.count} results"
      end
    end
  end

  protected

  def loot
    @loot = params.key?(:loot) ? Loot.new(loot_params) : Loot.new
  end

  def loot_params
    params[:loot].delete_if { |k,v| v.blank? }
    if params[:loot].empty?
      {}
    else
      params.require(:loot).permit(:name, :name_sanitize, :extension)
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_filter :authenticate_user!
  before_filter :already_authenticate

  def index
    @user = User.new
  end

  protected

  def already_authenticate
    redirect_to search_path if user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def toggle_nav_active(link)
    c = controller.controller_name
    m = controller.action_name
    klass = "active"
    if link == :search
      return klass if c == "search" 
    elsif link == :new_repository
      return klass if c == "repositories" && ["new", "create"].include?(m)
    elsif link == :repositories
      return klass if c == "repositories" && ["index", "show"].include?(m)
    end
    ""
  end

  # FIXME go decorator
  def class_for_alive(repository)
    if repository.alive?
      "success"
    else
      "danger"
    end
  end
end

app/views/authenticate/_form.html.haml
= form_for @user, url: signin_path, html: { id: :signin, class: "form-horizontal" }, method: :post do |f|
  .form-group
    = f.email_field :email, class: "form-control", placeholder: "Email"
  .form-group
    = f.password_field :password, class: "form-control", placeholder: "Password"
  .form-group
    = f.check_box :remember_me
    = f.label :remember_me
  = f.button "Connect", class: "btn btn-success pull-right"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Tiny Listing
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

  %body#tiny_listing
    %nav.navbar.navbar-default.navbar-inverse.navbar-fixed-top{:role => "navigation"}
      .navbar-header
        = link_to "Tiny Listing", search_path, class: "navbar-brand"
      - if user_signed_in?
        .collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li{class: toggle_nav_active(:search)}
              = link_to search_path do
                = fa_icon "search", text: "Search"
            %li{class: toggle_nav_active(:repositories)}
              = link_to repositories_path do
                = fa_icon "folder-o", text: "Repositories"
            %li{class: toggle_nav_active(:new_repository)}
              = link_to new_repository_path, class: "success-link" do
                = fa_icon "plus", text: "Add a repository"
          %ul.nav.navbar-nav.navbar-right
            %li
              = link_to signout_path, id: "logout", method: :delete do
                = fa_icon "power-off", text: "Logout"
    .content
      - if content_for?(:sub_header)
        .sub_header
          = yield(:sub_header)
      - if flash.notice
        .alert.alert-success
          = flash.notice
      - if flash.alert
        .alert.alert-danger
          = flash.alert
      = yield

app/views/loots/_loot.html.haml
%tr{id: dom_id(loot), class: "loot"}
  %td= loot.name
  %td= loot.extension
  %td= loot.size
  %td= link_to "Link to this loot", loot.link

app/views/repositories/_repository.html.haml
%tr{id: dom_id(repository), class: [:repository, class_for_alive(repository)]}
  %td= link_to(repository.link, repository.link)
  %td= repository.loots.count
  %td= link_to("Show", repository)

app/views/repositories/index.html.haml
%table.table.table-hover#loots
  %thead
    %th Link
    %th Number of loots 
    %th Show
  = render @repositories

app/views/repositories/new.html.haml
= content_for :sub_header do
  = form_for @repository, html: { class: "form-inline" } do |f|
    .form-group.main-control
      = f.text_field :link, class: "form-control", placeholder: "URL to the repository"
    = f.button "Add more treasures!", class: "btn btn-success"

= image_tag('repository-new-empty.svg', class: 'big-icon')

app/views/repositories/show.html.haml
= content_for(:sub_header) do
  .repository
    %h3= @repository.link
    %p
      #{@repository.loots.count} coins!
    .actions
      = link_to "Refresh", @repository, method: :patch, class: "btn btn-success"
%table.table#loots
  %thead
    %th Name
    %th Extension
    %th Size
    %th Link
  = render @repository.loots

app/views/search/_form.html.haml
= form_for @loot, url: search_path, html: { id: :search, class: "form-inline" }, method: :post do |f|
  .form-group.main-control
    = f.text_field :name, class: "form-control", placeholder: "Type your search here"
  .form-group
    = f.select :extension, Loot::BASIC_EXTENSIONS.collect {|ext| [ext, ext] }, { include_blank: true }, class: "form-control"
  = f.button "Bring the awesomness", class: "btn btn-success"

app/views/search/create.html.haml
= content_for(:sub_header) do
  = render 'form'
- if @loots.empty?
  %h1.center-text Oh noeesss!!
  = image_tag('no-result.svg', class: "big-icon")
- else
  %table.table#loots
    %thead
      %th Name
      %th Extension
      %th Size
      %th Link
    = render @loots

app/views/search/new.html.haml
= content_for(:sub_header) do
  = render 'form'
= image_tag('result-new-empty.svg', class: "big-icon")

app/views/welcome/index.html.haml
= render 'authenticate/form'